spring:
  application:
    name: membership-program

  datasource:
    url: jdbc:mysql://localhost:3306/membership_db
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true